---
service: bmi-results-blk
provider:
  name: aws
  runtime: python3.7
  region: eu-west-2
  package:
    individually: true
  deploymentBucket:
    name: com.serverless.${self:provider.region}.results.ons.deploys

custom:
  accounts: ${ssm:/aws/reference/secretsmanager/results-aws-accounts~true}
  accountId: ${self:custom.accounts.account-id}

  wranglers: ${ssm:/aws/reference/secretsmanager/results-bmi-sg-wranglers~true}
  ingest: ${self:custom.wranglers.ingest}
  enrichment: ${self:custom.wranglers.enrichment}
  imputation-movements: ${self:custom.wranglers.imputation-movements}
  imputation-means: ${self:custom.wranglers.imputation-means}
  imputation-iqrs: ${self:custom.wranglers.imputation-iqrs}
  imputation-atyps: ${self:custom.wranglers.imputation-atyps}
  imputation-recalc-means: ${self:custom.wranglers.imputation-recalc-means}
  imputation-calc-factors: ${self:custom.wranglers.imputation-calc-factors}
  imputation-apply-factors: ${self:custom.wranglers.imputation-apply-factors}
  aggregation-top2: ${self:custom.wranglers.aggregation-top2}
  aggregation-column: ${self:custom.wranglers.aggregation-column}
  aggregation-combiner: ${self:custom.wranglers.aggregation-combiner}
  disclosure-wrangler: ${self:custom.wranglers.disclosure-wrangler}
  all-gb-region: ${self:custom.wranglers.all-gb-region}
  error-capture: ${self:custom.wranglers.error-capture}
  method-return: ${self:custom.wranglers.method-return}

stepFunctions:
  stateMachines:
    ES-BMIBLK-Results:
      name: ES-BMIBLK-Results
      tags:
        app: results
      definition:
        Comment: Calls the lambdas required to run the BMI Blocks Survey.
        StartAt: Inputs
        States:
          Inputs:
            Next: Choice State
            Parameters:
              MessageStructure: json
              lookups.$: $.lookups
              additional_aggregated_column.$: $.additional_aggregated_column
              aggregated_column.$: $.aggregated_column
              aggregation_type.$: $.aggregation_type
              movement_type.$: $.movement_type
              cell_total_column.$: $.cell_total_column
              checkpoint.$: $.checkpoint
              disclosivity_marker.$: $.disclosivity_marker
              distinct_values.$: $.distinct_values
              explanation.$: $.explanation
              run_id.$: $.run_id
              period.$: $.period
              periodicity.$: $.periodicity
              period_column.$: $.period_column
              publishable_indicator.$: $.publishable_indicator
              queue_url.$: $.queue_url
              questions_list.$: $.questions_list
              raw_input_file.$: $.raw_input_file
              sum_columns.$: $.sum_columns
              survey.$: $.survey
              threshold.$: $.threshold
              top1_column.$: $.top1_column
              top2_column.$: $.top2_column
              total_columns.$: $.total_columns
              stage5_threshold.$: $.stage5_threshold
              disclosure_stages.$: $.disclosure_stages
              survey_column.$: $.survey_column
              factors_parameters.$: $.factors_parameters
              in_file_name.$: $.in_file_name
              marine_mismatch_check.$: $.marine_mismatch_check
              incoming_message_group.$: $.incoming_message_group
              out_file_name.$: $.out_file_name
              unique_identifier.$: $.unique_identifier
            Type: Pass

          Choice State:
            Choices:
              - Next: Ingest
                NumericEquals: 0
                Variable: $.checkpoint
              - Next: Enrichment
                NumericEquals: 1
                Variable: $.checkpoint
              - Next: Imputation Calculate Movements
                NumericEquals: 3
                Variable: $.checkpoint
              - Next: Aggregation
                NumericEquals: 4
                Variable: $.checkpoint
              - Next: Disclosure
                NumericEquals: 5
                Variable: $.checkpoint
            Type: Choice

          Ingest:
            Next: Enrichment
            Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.ingest}"  # yamllint disable-line rule:line-length
            Catch:
              - ErrorEquals: [States.ALL]
                Next: Failure
            Parameters:
              RuntimeVariables:
                run_id.$: $.run_id
                queue_url.$: $.queue_url
            ResultPath: $.data.lambdaresult
            Type: Task

          Enrichment:
            Next: Imputation Calculate Movements
            Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.enrichment}"  # yamllint disable-line rule:line-length
            Catch:
              - ErrorEquals: [States.ALL]
                ResultPath: $.error
                Next: Failure
            InputPath: $
            Parameters:
              RuntimeVariables:
                run_id.$: $.run_id
                lookups.$: $.lookups
                survey_column.$: $.survey_column
                queue_url.$: $.queue_url
                in_file_name.$: $.in_file_name
                incoming_message_group.$: $.incoming_message_group
                marine_mismatch_check.$: $.marine_mismatch_check
            ResultPath: $.data.lambdaresult
            Type: Task

          Imputation Calculate Movements:
            Next: Should Imputation Run
            Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-movements}"  # yamllint disable-line rule:line-length
            Catch:
              - ErrorEquals: [States.ALL]
                ResultPath: $.error
                Next: Failure
            InputPath: $
            Parameters:
              RuntimeVariables:
                run_id.$: $.run_id
                movement_type.$: $.movement_type
                period.$: $.period
                periodicity.$: $.periodicity
                period_column.$: $.period_column
                queue_url.$: $.queue_url
                questions_list.$: $.questions_list
                incoming_message_group.$: $.incoming_message_group
                in_file_name.$: $.in_file_name
            ResultPath: $.data.lambdaresult
            Type: Task

          Should Imputation Run:
            Choices:
              - BooleanEquals: true
                Next: Calculate Means
                Variable: $.data.lambdaresult.impute
              - BooleanEquals: false
                Next: Aggregation
                Variable: $.data.lambdaresult.impute
            Type: Choice

          Calculate Means:
            Next: Calculate IQRS
            Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-means}"  # yamllint disable-line rule:line-length
            Catch:
              - ErrorEquals: [States.ALL]
                Next: Failure
            InputPath: $
            Parameters:
              RuntimeVariables:
                run_id.$: $.run_id
                distinct_values.$: $.distinct_values
                queue_url.$: $.queue_url
                incoming_message_group.$: $.incoming_message_group
                in_file_name.$: $.in_file_name
                questions_list.$: $.questions_list
            ResultPath: $.data.lambdaresult
            Type: Task

          Calculate IQRS:
            Next: Calculate Atypicals
            Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-iqrs}"  # yamllint disable-line rule:line-length
            Catch:
              - ErrorEquals: [States.ALL]
                Next: Failure
            InputPath: $
            Parameters:
              RuntimeVariables:
                run_id.$: $.run_id
                distinct_values.$: $.distinct_values
                queue_url.$: $.queue_url
                incoming_message_group.$: $.incoming_message_group
                in_file_name.$: $.in_file_name
                questions_list.$: $.questions_list
            ResultPath: $.data.lambdaresult
            Type: Task

          Calculate Atypicals:
            Next: Calculate All-GB Region
            Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-atyps}"  # yamllint disable-line rule:line-length
            Catch:
              - ErrorEquals: [States.ALL]
                Next: Failure
            Parameters:
              RuntimeVariables:
                run_id.$: $.run_id
                queue_url.$: $.queue_url
                incoming_message_group.$: $.incoming_message_group
                in_file_name.$: $.in_file_name
                questions_list.$: $.questions_list
            ResultPath: $.data.lambdaresult
            Type: Task

          Calculate All-GB Region:
            Next: Re-Calculate Means
            Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.all-gb-region}"  # yamllint disable-line rule:line-length
            Catch:
              - ErrorEquals: [States.ALL]
                ResultPath: $.error
                Next: Failure
            InputPath: $
            Parameters:
              RuntimeVariables:
                run_id.$: $.run_id
                factors_parameters.$: $.factors_parameters
                queue_url.$: $.queue_url
                incoming_message_group.$: $.incoming_message_group
                in_file_name.$: $.in_file_name
            ResultPath: $.data.lambdaresult
            Type: Task

          Re-Calculate Means:
            Next: Calculate Factors
            Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-recalc-means}"  # yamllint disable-line rule:line-length
            Catch:
              - ErrorEquals: [States.ALL]
                ResultPath: $.error
                Next: Failure
            InputPath: $
            Parameters:
              RuntimeVariables:
                run_id.$: $.run_id
                distinct_values.$: $.distinct_values
                queue_url.$: $.queue_url
                questions_list.$: $.questions_list
                incoming_message_group.$: $.incoming_message_group
                in_file_name.$: $.in_file_name
            ResultPath: $.data.lambdaresult
            Type: Task

          Calculate Factors:
            Next: Apply Factors
            Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-calc-factors}"  # yamllint disable-line rule:line-length
            Catch:
              - ErrorEquals: [States.ALL]
                ResultPath: $.error
                Next: Failure
            InputPath: $
            Parameters:
              RuntimeVariables:
                run_id.$: $.run_id
                distinct_values.$: $.distinct_values
                period_column.$: $.period_column
                factors_parameters.$: $.factors_parameters
                queue_url.$: $.queue_url
                questions_list.$: $.questions_list
                incoming_message_group.$: $.incoming_message_group
                in_file_name.$: $.in_file_name
            ResultPath: $.data.lambdaresult
            Type: Task

          Apply Factors:
            Next: Aggregation
            Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-apply-factors}"  # yamllint disable-line rule:line-length
            Catch:
              - ErrorEquals: [States.ALL]
                ResultPath: $.error
                Next: Failure
            InputPath: $
            Parameters:
              RuntimeVariables:
                run_id.$: $.run_id
                period.$: $.period
                distinct_values.$: $.distinct_values
                sum_columns.$: $.sum_columns
                period_column.$: $.period_column
                factors_parameters.$: $.factors_parameters
                raw_input_file.$: $.raw_input_file
                queue_url.$: $.queue_url
                questions_list.$: $.questions_list
                incoming_message_group.$: $.incoming_message_group
                in_file_name.$: $.in_file_name
            ResultPath: $.data.lambdaresult
            Type: Task

          Aggregation:
            Type: Parallel
            Next: Combiner
            ResultPath: $
            OutputPath: $[0]
            Catch:
              - ErrorEquals: [States.ALL]
                ResultPath: $.error
                Next: Failure
            Branches:
              - StartAt: passRuntime
                States:
                  passRuntime:
                    Type: Pass
                    End: true

              - StartAt: County Total
                States:
                  County Total:
                    Type: Task
                    InputPath: $
                    Parameters:
                      RuntimeVariables:
                        run_id.$: $.run_id
                        aggregation_type.$: $.aggregation_type[1]
                        aggregated_column.$: $.aggregated_column
                        cell_total_column.$: $.cell_total_column[0]
                        total_columns.$: $.total_columns[1]
                        additional_aggregated_column.$: $.additional_aggregated_column
                        queue_url.$: $.queue_url
                        in_file_name:
                          aggregation_by_column.$: $.in_file_name.aggregation_by_column[0]
                    Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.aggregation-column}"  # yamllint disable-line rule:line-length
                    End: true

              - StartAt: EntRef Count
                States:
                  EntRef Count:
                    Type: Task
                    InputPath: $
                    Parameters:
                      RuntimeVariables:
                        run_id.$: $.run_id
                        aggregation_type.$: $.aggregation_type[0]
                        aggregated_column.$: $.aggregated_column
                        cell_total_column.$: $.cell_total_column[1]
                        total_columns.$: $.total_columns[0]
                        additional_aggregated_column.$: $.additional_aggregated_column
                        queue_url.$: $.queue_url
                        in_file_name:
                          aggregation_by_column.$: $.in_file_name.aggregation_by_column[0]
                    Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.aggregation-column}"  # yamllint disable-line rule:line-length
                    End: true

              - StartAt: Calculate Top2
                States:
                  Calculate Top2:
                    Type: Task
                    InputPath: $
                    Parameters:
                      RuntimeVariables:
                        run_id.$: $.run_id
                        aggregated_column.$: $.aggregated_column
                        additional_aggregated_column.$: $.additional_aggregated_column
                        top1_column.$: $.top1_column
                        top2_column.$: $.top2_column
                        total_columns.$: $.total_columns[1]
                        queue_url.$: $.queue_url
                        in_file_name:
                          aggregation_by_column.$: $.in_file_name.aggregation_by_column[0]
                    Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.aggregation-top2}"  # yamllint disable-line rule:line-length
                    End: true

          Combiner:
            Next: Disclosure
            Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.aggregation-combiner}"  # yamllint disable-line rule:line-length
            Catch:
              - ErrorEquals: [States.ALL]
                ResultPath: $.error
                Next: Failure
            ResultPath: $.data.lambdaresult
            OutputPath: $
            InputPath: $
            Parameters:
              RuntimeVariables:
                run_id.$: $.run_id
                aggregated_column.$: $.aggregated_column
                additional_aggregated_column.$: $.additional_aggregated_column
                queue_url.$: $.queue_url
                in_file_name:
                  aggregation_by_column.$: $.in_file_name.aggregation_by_column[0]
            Type: Task

          Disclosure:
            Next: Success
            Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.disclosure-wrangler}"  # yamllint disable-line rule:line-length
            Catch:
              - ErrorEquals: [States.ALL]
                ResultPath: $.error
                Next: Failure
            InputPath: $
            Parameters:
              RuntimeVariables:
                run_id.$: $.run_id
                unique_identifier.$: $.unique_identifier
                disclosivity_marker.$: $.disclosivity_marker
                publishable_indicator.$: $.publishable_indicator
                explanation.$: $.explanation
                total_columns.$: $.total_columns[1]
                parent_column.$: $.cell_total_column[1]
                threshold.$: $.threshold
                cell_total_column.$: $.cell_total_column[0]
                top1_column.$: $.top1_column
                top2_column.$: $.top2_column
                stage5_threshold.$: $.stage5_threshold
                disclosure_stages.$: $.disclosure_stages
                queue_url.$: $.queue_url
                out_file_name.$: $.out_file_name.disclosure
                in_file_name.$: $.in_file_name
            ResultPath: $.data.lambdaresult
            Type: Task

          Success:
            End: true
            Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.method-return}"  # yamllint disable-line rule:line-length
            InputPath: $
            ResultPath: $.data.lambdaresult
            Type: Task

          Failure:
            End: true
            Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.error-capture}"  # yamllint disable-line rule:line-length
            InputPath: $
            ResultPath: $.data.lambdaresult
            Type: Task

plugins:
  - serverless-step-functions
