service: es-bmi-results-sg
provider:
  name: aws
  runtime: python3.7
  region: eu-west-2
  package:
    individually: true

stepFunctions:
  stateMachines:
    ES-BMISG-Results:
        name: ES-BMISG-Results
        tags:
            app: results
        definition:
          Comment: Calls the lambdas required to run the BMI Sand and Gravel Survey
          StartAt: Inputs
          States:

            Inputs:
              Next: Choice State
              Parameters:
                MessageStructure: json
                RuntimeVariables:
                  checkpoint: 1
                  id.$: $.id
                  period.$: $.period
              Type: Pass

            Choice State:
              Choices:
              - Next: Enrichment
                NumericEquals: 1
                Variable: $.RuntimeVariables.checkpoint
              - Next: Strata
                NumericEquals: 2
                Variable: $.RuntimeVariables.checkpoint
              - Next: Imputation Calculate Movements
                NumericEquals: 3
                Variable: $.RuntimeVariables.checkpoint
              - Next: Aggregation
                NumericEquals: 4
                Variable: $.RuntimeVariables.checkpoint
              - Next: Disclosure
                NumericEquals: 5
                Variable: $.RuntimeVariables.checkpoint
              Type: Choice

            Enrichment:
              Next: Enrichment Outcome
              Resource: "arn:aws:lambda:eu-west-2:014669633018:function:es-enrichment-wrangler"
              ResultPath: $.data.lambdaresult
              Type: Task

            Enrichment Outcome:
              Choices:
              - BooleanEquals: true
                Next: Strata
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Strata:
              Next: Strata Outcome
              Resource: "arn:aws:lambda:eu-west-2:014669633018:function:es-strata-period-wrangler"
              ResultPath: $.data.lambdaresult
              Type: Task

            Strata Outcome:
              Choices:
              - BooleanEquals: true
                Next: Imputation Calculate Movements
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Imputation Calculate Movements:
              Next: Movements Outcome
              Resource: "arn:aws:lambda:eu-west-2:014669633018:function:es-calculate-movements-wrangler"
              ResultPath: $.data.lambdaresult
              Type: Task

            Movements Outcome:
              Choices:
              - BooleanEquals: true
                Next: Should Imputation Run
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Should Imputation Run:
              Choices:
              - BooleanEquals: true
                Next: Calculate Means
                Variable: $.data.lambdaresult.Impute
              - BooleanEquals: false
                Next: Success
                Variable: $.data.lambdaresult.Impute
              Type: Choice

            Calculate Means:
              Next: Means Outcome
              Resource: "arn:aws:lambda:eu-west-2:014669633018:function:es-calculate-means-wrangler"
              ResultPath: $.data.lambdaresult
              Type: Task

            Means Outcome:
              Choices:
              - BooleanEquals: true
                Next: Calculate IQRS
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Calculate IQRS:
              Next: IQRS Outcome
              Resource: "arn:aws:lambda:eu-west-2:014669633018:function:es-iqrs-wrangler"
              ResultPath: $.data.lambdaresult
              Type: Task

            IQRS Outcome:
              Choices:
              - BooleanEquals: true
                Next: Calculate Atypicals
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Calculate Atypicals:
              Next: Atypicals Outcome
              Resource: "arn:aws:lambda:eu-west-2:014669633018:function:es-atypicals-wrangler"
              ResultPath: $.data.lambdaresult
              Type: Task

            Atypicals Outcome:
              Choices:
              - BooleanEquals: true
                Next: Re-Calculate Means
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Re-Calculate Means:
              Next: Re-Calculate Means Outcome
              Resource: "arn:aws:lambda:eu-west-2:014669633018:function:es-recalculate-wrangler"
              ResultPath: $.data.lambdaresult
              Type: Task

            Re-Calculate Means Outcome:
              Choices:
              - BooleanEquals: true
                Next: Calculate Factors
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Calculate Factors:
              Next: Factors Outcome
              Resource: "arn:aws:lambda:eu-west-2:014669633018:function:es-calculate-factors-wrangler"
              ResultPath: $.data.lambdaresult
              Type: Task

            Factors Outcome:
              Choices:
              - BooleanEquals: true
                Next: Apply Factors
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Apply Factors:
              Next: Apply Outcome
              Resource: "arn:aws:lambda:eu-west-2:014669633018:function:es-apply-factors-wrangler"
              ResultPath: $.data.lambdaresult
              Type: Task

            Apply Outcome:
              Choices:
              - BooleanEquals: true
                Next: Aggregation
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Aggregation:
              Type: Parallel
              Next: Combiner
              Branches:
                - StartAt: County Total
                  States:
                    County Total:
                      Type: Task
                      Resource: "arn:aws:lambda:eu-west-2:014669633018:function:es-aggregation-county-wrangler"
                      End: true

                - StartAt: EntRef Count
                  States:
                    EntRef Count:
                      Type: Task
                      Resource: "arn:aws:lambda:eu-west-2:014669633018:function:es-aggregation-entref-wrangler"
                      End: true

                - StartAt: Calculate Top2
                  States:
                    Calculate Top2:
                      Type: Task
                      Resource: "arn:aws:lambda:eu-west-2:014669633018:function:es-aggregation-top2-wrangler"
                      End: true

            Combiner:
              Next: Combiner Outcome
              Resource: "arn:aws:lambda:eu-west-2:014669633018:function:es-aggregation-combiner-wrangler"
              ResultPath: $.data.lambdaresult
              Type: Task

            Combiner Outcome:
              Choices:
              - BooleanEquals: true
                Next: Stage 1
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Stage 1:
              Next: Stage 1 Outcome
              Resource: "arn:aws:lambda:eu-west-2:014669633018:function:es-disclosure-stage-1-wrangler"
              ResultPath: $.data.lambdaresult
              Type: Task

            Stage 1 Outcome:
              Choices:
              - BooleanEquals: true
                Next: Stage 2
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Stage 2:
              Next: Stage 2 Outcome
              Resource: "arn:aws:lambda:eu-west-2:014669633018:function:es-disclosure-stage-2-wrangler"
              ResultPath: $.data.lambdaresult
              Type: Task

            Stage 2 Outcome:
              Choices:
              - BooleanEquals: true
                Next: Stage 5
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Stage 5:
              Next: Stage 5 Outcome
              Resource: "arn:aws:lambda:eu-west-2:014669633018:function:es-disclosure-stage-5-wrangler"
              ResultPath: $.data.lambdaresult
              Type: Task

            Stage 5 Outcome:
              Choices:
              - BooleanEquals: true
                Next: Success
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Success:
              End: true
              Resource: "arn:aws:lambda:eu-west-2:014669633018:function:success_handler"
              ResultPath: $.data.lambdaresult
              Type: Task

            Failure:
              End: true
              Resource: "arn:aws:lambda:eu-west-2:014669633018:function:runtime_error_capture"
              ResultPath: $.data.lambdaresult
              Type: Task

plugins:
  - serverless-step-functions