service: aws-python-test
provider:
  name: aws
  runtime: python3.7
  region: eu-west-2
  package:
    individually: true

custom:
  accounts: ${ssm:/aws/reference/secretsmanager/results-aws-accounts~true}
  accountId: ${self:custom.accounts.account-id}

  wranglers: ${ssm:/aws/reference/secretsmanager/results-bmi-sg-wranglers~true}

  ingest: ${self:custom.wranglers.ingest}
  enrichment: ${self:custom.wranglers.enrichment}
  strata: ${self:custom.wranglers.strata}
  imputation-movements: ${self:custom.wranglers.imputation-movements}
  imputation-means: ${self:custom.wranglers.imputation-means}
  imputation-iqrs: ${self:custom.wranglers.imputation-iqrs}
  imputation-atyps: ${self:custom.wranglers.imputation-atyps}
  imputation-recal-means: ${self:custom.wranglers.imputation-recal-means}
  imputation-calc-factors: ${self:custom.wranglers.imputation-calc-factors}
  imputation-apply-factors: ${self:custom.wranglers.imputation-apply-factors}
  aggregation-top2: ${self:custom.wranglers.aggregation-top2}
  aggregation-entref: ${self:custom.wranglers.aggregation-entref}
  aggregation-county: ${self:custom.wranglers.aggregation-county}
  aggregation-combiner: ${self:custom.wranglers.aggregation-combiner}
  disclosure-stage1: ${self:custom.wranglers.disclosure-stage1}
  disclosure-stage2: ${self:custom.wranglers.disclosure-stage2}
  disclosure-stage5: ${self:custom.wranglers.disclosure-stage5}
  error-capture: ${self:custom.wranglers.error-capture}
  method-return: ${self:custom.wranglers.method-return}

stepFunctions:
  stateMachines:
    ES-BMISG-Results:
        name: ES-BMISG-Results
        tags:
            app: results
        definition:
          Comment: Calls the lambdas required to run the BMI Sand and Gravel Survey
          StartAt: Inputs
          States:

            Inputs:
              Next: Choice State
              Parameters:
                MessageStructure: json
                RuntimeVariables:
                  checkpoint: 1
                  id.$: $.id
                  period.$: $.period
              Type: Pass

            Choice State:
              Choices:
              - Next: Ingest
                NumericEquals: 0
                Variable: $.RuntimeVariables.checkpoint
              - Next: Enrichment
                NumericEquals: 1
                Variable: $.RuntimeVariables.checkpoint
              - Next: Strata
                NumericEquals: 2
                Variable: $.RuntimeVariables.checkpoint
              - Next: Imputation Calculate Movements
                NumericEquals: 3
                Variable: $.RuntimeVariables.checkpoint
              - Next: Aggregation
                NumericEquals: 4
                Variable: $.RuntimeVariables.checkpoint
              - Next: Stage 1
                NumericEquals: 5
                Variable: $.RuntimeVariables.checkpoint
              Type: Choice

            Ingest:
              Next: Ingest Outcome
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.ingest}"
              ResultPath: $.data.lambdaresult
              Type: Task

            Ingest Outcome:
              Choices:
                - BooleanEquals: true
                  Next: Enrichment
                  Variable: $.data.lambdaresult.success
                - BooleanEquals: false
                  Next: Failure
                  Variable: $.data.lambdaresult.success
              Type: Choice

            Enrichment:
              Next: Enrichment Outcome
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.enrichment}"
              ResultPath: $.data.lambdaresult
              Type: Task

            Enrichment Outcome:
              Choices:
              - BooleanEquals: true
                Next: Strata
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Strata:
              Next: Strata Outcome
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.strata}"
              ResultPath: $.data.lambdaresult
              Type: Task

            Strata Outcome:
              Choices:
              - BooleanEquals: true
                Next: Imputation Calculate Movements
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Imputation Calculate Movements:
              Next: Movements Outcome
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-movements}"
              ResultPath: $.data.lambdaresult
              Type: Task

            Movements Outcome:
              Choices:
              - BooleanEquals: true
                Next: Should Imputation Run
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Should Imputation Run:
              Choices:
              - BooleanEquals: true
                Next: Calculate Means
                Variable: $.data.lambdaresult.Impute
              - BooleanEquals: false
                Next: Success
                Variable: $.data.lambdaresult.Impute
              Type: Choice

            Calculate Means:
              Next: Means Outcome
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-means}"
              ResultPath: $.data.lambdaresult
              Type: Task

            Means Outcome:
              Choices:
              - BooleanEquals: true
                Next: Calculate IQRS
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Calculate IQRS:
              Next: IQRS Outcome
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputations-iqrs}"
              ResultPath: $.data.lambdaresult
              Type: Task

            IQRS Outcome:
              Choices:
              - BooleanEquals: true
                Next: Calculate Atypicals
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Calculate Atypicals:
              Next: Atypicals Outcome
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-atyps}"
              ResultPath: $.data.lambdaresult
              Type: Task

            Atypicals Outcome:
              Choices:
              - BooleanEquals: true
                Next: Re-Calculate Means
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Re-Calculate Means:
              Next: Re-Calculate Means Outcome
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-recal-means}"
              ResultPath: $.data.lambdaresult
              Type: Task

            Re-Calculate Means Outcome:
              Choices:
              - BooleanEquals: true
                Next: Calculate Factors
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Calculate Factors:
              Next: Factors Outcome
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-calc-factors}"
              ResultPath: $.data.lambdaresult
              Type: Task

            Factors Outcome:
              Choices:
              - BooleanEquals: true
                Next: Apply Factors
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Apply Factors:
              Next: Apply Outcome
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-apply-factors}"
              ResultPath: $.data.lambdaresult
              Type: Task

            Apply Outcome:
              Choices:
              - BooleanEquals: true
                Next: Aggregation
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Aggregation:
              Type: Parallel
              Next: Combiner
              Branches:
                - StartAt: County Total
                  States:
                    County Total:
                      Type: Task
                      Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.aggregation-county}"
                      End: true

                - StartAt: EntRef Count
                  States:
                    EntRef Count:
                      Type: Task
                      Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.aggregation-entref}"
                      End: true

                - StartAt: Calculate Top2
                  States:
                    Calculate Top2:
                      Type: Task
                      Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.aggregation-top2}"
                      End: true

            Combiner:
              Next: Combiner Outcome
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.aggregation-combiner}"
              ResultPath: $.data.lambdaresult
              Type: Task

            Combiner Outcome:
              Choices:
              - BooleanEquals: true
                Next: Stage 1
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Stage 1:
              Next: Stage 1 Outcome
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.disclosure-stage1}"
              ResultPath: $.data.lambdaresult
              Type: Task

            Stage 1 Outcome:
              Choices:
              - BooleanEquals: true
                Next: Stage 2
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Stage 2:
              Next: Stage 2 Outcome
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.disclosure-stage2}"
              ResultPath: $.data.lambdaresult
              Type: Task

            Stage 2 Outcome:
              Choices:
              - BooleanEquals: true
                Next: Stage 5
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Stage 5:
              Next: Stage 5 Outcome
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.disclosure-stage5}"
              ResultPath: $.data.lambdaresult
              Type: Task

            Stage 5 Outcome:
              Choices:
              - BooleanEquals: true
                Next: Success
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Success:
              End: true
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.method-return}"
              ResultPath: $.data.lambdaresult
              Type: Task

            Failure:
              End: true
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.error-capture}"
              ResultPath: $.data.lambdaresult
              Type: Task

plugins:
  - serverless-step-functions
