service: aws-python-example
provider:
  name: aws
  runtime: python3.7
  region: eu-west-2
  package:
    individually: true

stepFunctions:
  stateMachines:
    ES-BMISG-Results:
        name: ES-BMISG-Results
        tags:
            app: results
        definition:
          Comment: Calls the lambdas required to run the BMI Sand and Gravel Survey
          StartAt: Inputs
          States:

            Inputs:
              Next: Choice State
              Parameters:
                MessageStructure: json
                RuntimeVariables:
                  checkpoint: 1
                  id.$: $.id
                  period.$: $.period
              Type: Pass

            Choice State:
              Choices:
              - Next: Enrichment
                NumericEquals: 1
                Variable: $.RuntimeVariables.checkpoint
              - Next: Strata
                NumericEquals: 2
                Variable: $.RuntimeVariables.checkpoint
              - Next: Imputation Calculate Movements
                NumericEquals: 3
                Variable: $.RuntimeVariables.checkpoint
              Type: Choice

            Enrichment:
              Next: Enrichment Outcome
              Resource:
                Fn::getAtt: [esDashenrichmentDashwranglerLambdaFunction,Arn]
              ResultPath: $.data.lambdaresult
              Type: Task

            Enrichment Outcome:
              Choices:
              - BooleanEquals: true
                Next: Strata
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Strata:
              Next: Strata Outcome
              Resource:
               Fn::getAtt: [esDashstrataDashperiodDashwranglerLambdaFunction,Arn]
              ResultPath: $.data.lambdaresult
              Type: Task

            Strata Outcome:
              Choices:
              - BooleanEquals: true
                Next: Imputation Calculate Movements
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Imputation Calculate Movements:
              Next: Movements Outcome
              Resource:
                Fn::getAtt: [esDashcalculateDashmovementDashwranglerLambdaFunction,Arn]
              ResultPath: $.data.lambdaresult
              Type: Task

            Movements Outcome:
              Choices:
              - BooleanEquals: true
                Next: Should Imputation Run
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Should Imputation Run:
              Choices:
              - BooleanEquals: true
                Next: Calculate Means
                Variable: $.data.lambdaresult.Impute
              - BooleanEquals: false
                Next: Success
                Variable: $.data.lambdaresult.Impute
              Type: Choice

            Calculate Means:
              Next: Means Outcome
              Resource:
                Fn::getAtt: [esDashcalculateDashmeansDashwranglerLambdaFunction,Arn]
              ResultPath: $.data.lambdaresult
              Type: Task

            Means Outcome:
              Choices:
              - BooleanEquals: true
                Next: Calculate IQRS
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Calculate IQRS:
              Next: IQRS Outcome
              Resource:
                Fn::getAtt: [esDashiqrsDashwranglerLambdaFunction,Arn]
              ResultPath: $.data.lambdaresult
              Type: Task

            IQRS Outcome:
              Choices:
              - BooleanEquals: true
                Next: Calculate Atypicals
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Calculate Atypicals:
              Next: Atypicals Outcome
              Resource:
                Fn::getAtt: [esDashatypicalsDashwranglerLambdaFunction,Arn]
              ResultPath: $.data.lambdaresult
              Type: Task

            Atypicals Outcome:
              Choices:
              - BooleanEquals: true
                Next: Re-Calculate Means
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Re-Calculate Means:
              Next: Re-Calculate Means Outcome
              Resource:
                Fn::getAtt: [esDashrecalculateDashmeansDashwranglerLambdaFunction,Arn]
              ResultPath: $.data.lambdaresult
              Type: Task

            Re-Calculate Means Outcome:
              Choices:
              - BooleanEquals: true
                Next: Calculate Factors
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Calculate Factors:
              Next: Factors Outcome
              Resource:
                Fn::getAtt: [esDashcalculateDashfactorsDashwranglerLambdaFunction,Arn]
              ResultPath: $.data.lambdaresult
              Type: Task

            Factors Outcome:
              Choices:
              - BooleanEquals: true
                Next: Apply Factors
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Apply Factors:
              Next: Apply Outcome
              Resource:
                Fn::getAtt: [esDashapplyDashfactorsDashwranglerLambdaFunction,Arn]
              ResultPath: $.data.lambdaresult
              Type: Task

            Apply Outcome:
              Choices:
              - BooleanEquals: true
                Next: Aggregation
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Aggregation:
              Type: Parallel
              Next: Combiner
              Branches:
                - StartAt: County Total
                  States:
                    County Total:
                      Type: Task
                      Resource:
                        Fn::getAtt: [esDashaggregationDashcountyDashwranglerLambdaFunction,Arn]
                      End: true

                - StartAt: EntRef Count
                  States:
                    EntRef Count:
                      Type: Task
                      Resource:
                        Fn::getAtt: [esDashaggregationDashentrefDashwranglerLambdaFunction,Arn]
                      End: true

                - StartAt: Calculate Top2
                  States:
                    Calculate Top2:
                      Type: Task
                      Resource:
                        Fn::getAtt: [esDashaggregationDashtop2DashwranglerLambdaFunction,Arn]
                      End: true

            Combiner:
              Next: Combiner Outcome
              Resource:
                Fn::getAtt: [esDasgaggregationDashcombinerLambdaFunction,Arn]
              ResultPath: $.data.lambdaresult
              Type: Task

            Combiner Outcome:
              Choices:
              - BooleanEquals: true
                Next: Stage 1
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Stage 1:
              Next: Stage 1 Outcome
              Resource:
                Fn::getAtt: [esDashdisclosureDashstage1DashwranglerLambdaFunction,Arn]
              ResultPath: $.data.lambdaresult
              Type: Task

            Stage 1 Outcome:
              Choices:
              - BooleanEquals: true
                Next: Stage 2
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Stage 2:
              Next: Stage 2 Outcome
              Resource:
                Fn::getAtt: [esDashdisclosureDashstage2DashwranglerLambdaFunction,Arn]
              ResultPath: $.data.lambdaresult
              Type: Task

            Stage 2 Outcome:
              Choices:
              - BooleanEquals: true
                Next: Stage 5
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Stage 5:
              Next: Stage 5 Outcome
              Resource:
                Fn::getAtt: [esDashdisclosureDashstage5DashwranglerLambdaFunction,Arn]
              ResultPath: $.data.lambdaresult
              Type: Task

            Stage 5 Outcome:
              Choices:
              - BooleanEquals: true
                Next: Success
                Variable: $.data.lambdaresult.success
              - BooleanEquals: false
                Next: Failure
                Variable: $.data.lambdaresult.success
              Type: Choice

            Success:
              End: true
              Resource:
                Fn::getAtt: [es_statistical_method_returnLambdaFunction,Arn]
              ResultPath: $.data.lambdaresult
              Type: Task

            Failure:
              End: true
              Resource:
                Fn::getAtt: [runtime_error_captureLambdaFunction,Arn]
              ResultPath: $.data.lambdaresult
              Type: Task

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters