service: bmi-results-sg
provider:
  name: aws
  runtime: python3.7
  region: eu-west-2
  package:
    individually: true
  deploymentBucket:
    name: com.serverless.${self:provider.region}.results.ons.deploys

custom:
  accounts: ${ssm:/aws/reference/secretsmanager/results-aws-accounts~true}
  accountId: ${self:custom.accounts.account-id}

  wranglers: ${ssm:/aws/reference/secretsmanager/results-bmi-sg-wranglers~true}
  ingest: ${self:custom.wranglers.ingest}
  enrichment: ${self:custom.wranglers.enrichment}
  strata: ${self:custom.wranglers.strata}
  imputation-movements: ${self:custom.wranglers.imputation-movements}
  imputation-means: ${self:custom.wranglers.imputation-means}
  imputation-iqrs: ${self:custom.wranglers.imputation-iqrs}
  imputation-atyps: ${self:custom.wranglers.imputation-atyps}
  imputation-recalc-means: ${self:custom.wranglers.imputation-recalc-means}
  imputation-calc-factors: ${self:custom.wranglers.imputation-calc-factors}
  imputation-apply-factors: ${self:custom.wranglers.imputation-apply-factors}
  aggregation-top2: ${self:custom.wranglers.aggregation-top2}
  aggregation-entref: ${self:custom.wranglers.aggregation-entref}
  aggregation-county: ${self:custom.wranglers.aggregation-county}
  aggregation-combiner: ${self:custom.wranglers.aggregation-combiner}
  disclosure-stage1: ${self:custom.wranglers.disclosure-stage1}
  disclosure-stage2: ${self:custom.wranglers.disclosure-stage2}
  disclosure-stage5: ${self:custom.wranglers.disclosure-stage5}
  error-capture: ${self:custom.wranglers.error-capture}
  method-return: ${self:custom.wranglers.method-return}

stepFunctions:
  stateMachines:
    ES-BMISG-Results:
        name: ES-BMISG-Results
        tags:
            app: results
        definition:
          Comment: Calls the lambdas required to run the BMI Sand and Gravel Survey
          StartAt: Inputs
          States:

            Inputs:
              Next: Choice State
              Parameters:
                MessageStructure: json
                RuntimeVariables:
                  checkpoint.$: $.checkpoint
                  id.$: $.id
                  period.$: $.period
                  calculation_type.$: $.calculation_type
                  distinct_values.$: $.distinct_values
                  disclosivity_marker.$: $.disclosivity_marker
                  publishable_indicator.$: $.publishable_indicator
                  explanation.$: $.explanation
                  total_column.$: $.total_column
                  parent_column.$: $.parent_column
                  top1_column.$: $.top1_column
                  top2_column.$: $.top2_column
                  threshold.$: $.threshold
                  aggA.$: $.aggA
                  period_column.$: $.period_column
                  aggB.$: $.aggB
              Type: Pass

            Choice State:
              Choices:
              - Next: Ingest
                NumericEquals: 0
                Variable: $.RuntimeVariables.checkpoint
              - Next: Enrichment
                NumericEquals: 1
                Variable: $.RuntimeVariables.checkpoint
              - Next: Strata
                NumericEquals: 2
                Variable: $.RuntimeVariables.checkpoint
              - Next: Imputation Calculate Movements
                NumericEquals: 3
                Variable: $.RuntimeVariables.checkpoint
              - Next: Aggregation
                NumericEquals: 4
                Variable: $.RuntimeVariables.checkpoint
              - Next: Disclosure Stage 1
                NumericEquals: 5
                Variable: $.RuntimeVariables.checkpoint
              Type: Choice

            Ingest:
              Next: Enrichment
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.ingest}"
              Catch:
                - ErrorEquals: [States.ALL]
                  Next : Failure
              ResultPath: $.data.lambdaresult
              Type: Task

            Enrichment:
              Next: Strata
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.enrichment}"
              Catch:
                - ErrorEquals: [States.ALL]
                  Next: Failure
              ResultPath: $.data.lambdaresult
              Type: Task

            Strata:
              Next: Imputation Calculate Movements
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.strata}"
              Catch:
                - ErrorEquals: [States.ALL]
                  Next: Failure
              ResultPath: $.data.lambdaresult
              Type: Task

            Imputation Calculate Movements:
              Next: Should Imputation Run
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-movements}"
              Catch:
                - ErrorEquals: [States.ALL]
                  Next: Failure
              ResultPath: $.data.lambdaresult
              Type: Task

            Should Imputation Run:
              Choices:
              - BooleanEquals: true
                Next: Calculate Means
                Variable: $.data.lambdaresult.impute
              - BooleanEquals: false
                Next: Success
                Variable: $.data.lambdaresult.impute
              Type: Choice

            Calculate Means:
              Next: Calculate IQRS
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-means}"
              Catch:
                - ErrorEquals: [States.ALL]
                  Next: Failure
              ResultPath: $.data.lambdaresult
              Type: Task

            Calculate IQRS:
              Next: Calculate Atypicals
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-iqrs}"
              Catch:
                - ErrorEquals: [States.ALL]
                  Next: Failure
              ResultPath: $.data.lambdaresult
              Type: Task

            Calculate Atypicals:
              Next: Re-Calculate Means
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-atyps}"
              Catch:
                - ErrorEquals: [States.ALL]
                  Next: Failure
              ResultPath: $.data.lambdaresult
              Type: Task

            Re-Calculate Means:
              Next: Calculate Factors
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-recalc-means}"
              Catch:
                - ErrorEquals: [States.ALL]
                  Next: Failure
              ResultPath: $.data.lambdaresult
              Type: Task

            Calculate Factors:
              Next: Apply Factors
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-calc-factors}"
              Catch:
                - ErrorEquals: [States.ALL]
                  Next: Failure
              ResultPath: $.data.lambdaresult
              Type: Task

            Apply Factors:
              Next: Aggregation
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.imputation-apply-factors}"
              Catch:
                - ErrorEquals: [States.ALL]
                  Next: Failure
              ResultPath: $.data.lambdaresult
              Type: Task

            Aggregation:
              Type: Parallel
              Next: Combiner
              ResultPath: $
              OutputPath: $
              Branches:
                - StartAt: passRuntime
                  States:
                    passRuntime:
                      Type: Pass
                      End: true
                - StartAt: County Total
                  States:
                    County Total:
                      Type: Task
                      InputPath: $.RuntimeVariables.aggA
                      Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.aggregation-county}"
                      End: true

                - StartAt: EntRef Count
                  States:
                    EntRef Count:
                      Type: Task
                      InputPath: $.RuntimeVariables.aggB
                      Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.aggregation-entref}"
                      End: true

                - StartAt: Calculate Top2
                  States:
                    Calculate Top2:
                      Type: Task
                      Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.aggregation-top2}"
                      End: true

            Combiner:
              Next: Disclosure Stage 1
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.aggregation-combiner}"
              Catch:
                - ErrorEquals: [States.ALL]
                  Next: Failure
              ResultPath: $[0].data.lambdaresult
              OutputPath: $
              InputPath: $
              Type: Task

            Disclosure Stage 1:
              Next: Disclosure Stage 2
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.disclosure-stage1}"
              Catch:
                - ErrorEquals: [States.ALL]
                  Next: Failure
              InputPath: $[0]
              ResultPath: $[0].data.lambdaresult
              Type: Task

            Disclosure Stage 2:
              Next: Disclosure Stage 5
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.disclosure-stage2}"
              Catch:
                - ErrorEquals: [States.ALL]
                  Next: Failure
              InputPath: $[0]
              ResultPath: $[0].data.lambdaresult
              Type: Task

            Disclosure Stage 5:
              Next: Success
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.disclosure-stage5}"
              Catch:
                - ErrorEquals: [States.ALL]
                  Next: Failure
              InputPath: $[0]
              ResultPath: $[0].data.lambdaresult
              Type: Task

            Success:
              End: true
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.method-return}"
              InputPath: $[0]
              ResultPath: $[0].data.lambdaresult
              Type: Task

            Failure:
              End: true
              Resource: "arn:aws:lambda:eu-west-2:${self:custom.accountId}:function:${self:custom.error-capture}"
              InputPath: $[0]
              ResultPath: $[0].data.lambdaresult
              Type: Task

plugins:
  - serverless-step-functions
